### ISSUE TITLE
node exited with code: 1

### ISSUE THREAD

**Issue by Dooez** [jedrzejboczar/nvim-dap-cortex-debug#11]
The latest commit [d35c52d](https://github.com/jedrzejboczar/nvim-dap-cortex-debug/commit/d35c52dc2dedd0b139fde7c1c830b79c3a6a2944) results in `node exited with code: 1` error message.

[[b6f1bec] ](https://github.com/jedrzejboczar/nvim-dap-cortex-debug/commit/b6f1bece043e9b3d8d9656d8b62205077fe64aaf) works fine.

DapShowLog is very big, but i can provide it if would be helpful.

**Comment by jedrzejboczar** [comment]
Yes, please provide nvim-dap log and enable `debug = true` in setup od nvim-dap-cortex-debug (messages would be in `:Notifications` if using vim-notify. I don't know what in the recent changes could lead to the node cortex-debug extension dying. Just to confirm: you made no other changes to nvim configuration when this started appearing?

**Comment by Dooez** [comment]
I've retested 2 configs with only difference being presence of ` commit = "b6f1bec",` in lazy plugin configuration.
With older commit everything works.
Dap log on the newest version is attached.
[dap.log](https://github.com/user-attachments/files/17132218/dap.log)

**Comment by Dooez** [comment]
I've rechecked and 6056de8f90736e62e318537e4415eab351487611 is actually the latest working version. Sorry for the wrong info.

**Comment by jedrzejboczar** [comment]
Can you please test latest master? 

If it still doesn't work then please provide the DAP configuration that you are using.

**Comment by Dooez** [comment]
The latest master works. Thank you.
