### ISSUE TITLE
"DAP Scopes" has no variables to display, and something wrong happened

### ISSUE THREAD

**Issue by liuyangzys** [jedrzejboczar/nvim-dap-cortex-debug#2]
nvim  v0.9.1
cortex-debug v1.12.0

Something wrong happened as shown as bellow, I don't know how to describe it.

![image](https://github.com/jedrzejboczar/nvim-dap-cortex-debug/assets/19203871/f38e6918-9d45-47a2-8d0b-83a6437661a7)

**Comment by jedrzejboczar** [comment]
Thanks for report. The error is a bit strange, seams like `response.variables` is now list of objects of type `userdata`? Maybe something changed in nvim-dap. I won't have time to look into this for the next week, but I'll try after that.

**Comment by jedrzejboczar** [comment]
This should now be fixed.
