### ISSUE TITLE
node exited with code: 1

### ISSUE THREAD

**Issue by hilpara** [jedrzejboczar/nvim-dap-cortex-debug#4]
After starting the debugger, I get a message DAP: node exited with code: 1. How can I debug this failure? I'm new to whole lua and nvim world, but I'm willing to try. Or do you already know what it could be?
I'm using nvim.dap (1c63f37), cortex-debug 1.12.0, node 20.5.0 and macOS (if it makes any difference).

**Comment by jedrzejboczar** [comment]
Hi, sorry for late response but I was not really available lately. You can use the command `DapSetLogLevel debug`, then try to launch the debugger. Then you can change back to `DapSetLogLevel info` (to avoid spam in the log file) and use `DapShowLog` to view the logfile. You can search for the `node` command, there should be something like:
```
[ DEBUG ] 2023-08-16T11:59:35Z+0200 ] .../.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1296 ]	"Spawning debug adapter"	{
  args = { "/home/jb/.vscode/extensions/marus25.cortex-debug-1.10.0/dist/debugadapter.js" },
  command = "node",
  enrich_config = <function 1>,
  options = {
    detached = false
  },
  type = "executable"
}
```
I suppose that the path to debugadapter.js might be incorrect, if so you'll need to update the `extension_path` in the setup function of this plugin.

**Comment by hilpara** [comment]
Thanks for the respomse.

The checkhealth shows:
```
nvim-dap-cortex-debug ~
- OK Node.js installed: v20.5.0
- OK cortex-debug extension found
- OK Found debugadapter.js

```

My setup:
```
  require("dap-cortex-debug").setup({
  debug = false, -- log debug messages
  extension_path = "~/.vscode-oss/extensions/marus25.cortex-debug-1.12.0-universal/dist",
  lib_extension = nil, -- tries auto-detecting, e.g. 'so' on unix
  node_path = "node", -- path to node.js executable
  dapui_rtt = false, -- register nvim-dap-ui RTT element
  dap_vscode_filetypes = { "c", "cpp" }, -- make :DapLoadLaunchJSON register cortex-debug for C/C++, set false to disable
})

require("dap.ext.vscode").load_launchjs(nil, { cppdbg = { "c", "cpp" } })
```

And the debug log:

```
[ ERROR ] 2023-08-16T12:18:18Z+0200 ] .../.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1426 ]	"stderr"	{
  args = { "/Users/hilpara/Sources/Temp/nvim-test/v:null" },
  command = "node",
  enrich_config = <function 1>,
  options = {
    detached = false
  },
```


So why is the arg wrong even if the check founds the debugadapter.js? I did try with /.vscode-oss/extensions/marus25.cortex-debug-*/, but the then the check says it could not find it.

**Comment by jedrzejboczar** [comment]
Ok, you have to provide path without `/dist` at the end, so `extension_path = "~/.vscode-oss/extensions/marus25.cortex-debug-1.12.0-universal/",`. 

And I found a bug in my implementation of checkhealth - it uses `vim.fn.filereadable(debugadapter_path)` in the condition, but those vim functions return 0 or 1 and in Lua both of these are converted to boolean `true`. I'll fix this when I find a moment. I should also add a check that we found the path to debugadapter.js in the adapter function.

**Comment by hilpara** [comment]
Thanks At least it tries to start debugging now. Now I just need to find out why it can't connect to target. With the same debug configuration I can launch it on vscode.

**Comment by jedrzejboczar** [comment]
Hope that it will work soon. You can look at the DAP debug logs (`DapSetLogLevel`, `DapShowLog`) and also check the GDB server console (search for Neovim buffer called `cortex-debug://gdb-server-console:X` where X will be a number). You can compare the output to the one in VSCode.
